spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: https://user-service.orangebay-0b927206.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /api/${segment}

        - id: scheduling-service
          uri: http://52.6.97.237:8082
          predicates:
            - Path=/api/sessions,/api/sessions/**
          filters:
            - RewritePath=/api/sessions(?<segment>/?.*), /sessions${segment}

        - id: offer-service
          uri: https://offer-service.orangebay-0b927206.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/offers/**

        - id: event-service
          uri: ${EVENT_SERVICE_URI:http://52.230.166.43:3000}
          predicates:
            - Path=/api/events/**

        - id: video-service-chat-api
          uri: http://52.230.166.43:3000
          predicates:
            - Path=/api/chat/**

        - id: video-service-socket
          uri: ws://52.230.166.43:3000
          predicates:
            - Path=/socket.io/**

        - id: group-session-service
          uri: https://group-session-service.orangebay-0b927206.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/group-sessions/**

        - id: notification-service
          uri: https://notification-service.orangebay-0b927206.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/notifications/**

server:
  port: 8080

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
