spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: scheduling-service
          uri: lb://scheduling-service
          predicates:
            - Path=/api/sessions/**

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**

        - id: offer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/offers/**

server:
  port: 8080

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway